name: Deploy to Vultr (PM2)

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check SSH_KEY present
        run: |
          if [ -z "${{ secrets.SSH_KEY }}" ]; then
            echo "❌ SSH_KEY secret is missing or empty. Create it in Repo Settings → Secrets (Actions) or point to the correct Environment."
            exit 1
          fi

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Rsync repo to server
        run: |
          rsync -az --delete \
            --exclude '.env' \
            --exclude 'config/' \
            -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SERVER_APP_DIR }}/

      - name: Install & build & restart
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd "${{ secrets.SERVER_APP_DIR }}"
            # Instala dependencias
            npm ci
            # Arranca/reinicia
            pm2 describe gamification >/dev/null 2>&1 && pm2 restart gamification || pm2 start --name gamification node gamification.js
            pm2 save
          EOF
